spring.application.name=FirstLevelReccommadtionModel

spring.datasource.url=jdbc:postgresql://localhost:5433/RecommandationService?schemaName=public
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hinernate.default_schema=company
# JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL95Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.output.ansi.enabled=always