sonar.projectKey=wishlist-service
sonar.projectName=Wishlist Service
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=admin
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
